# 此备份文件使用国内镜像源，已经在 .dockerignore 中排除
FROM ghcr.nju.edu.cn/pytorch/pytorch:2.11.0-cuda13.0-cudnn9-runtime

# 不生成 .pyc 文件
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# 设置工作目录
WORKDIR /app

# 安装依赖，容器内可以 --break-system-packages
COPY requirements.txt .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple --break-system-packages -r requirements.txt

# 复制代码
COPY . .

# 暴露端口
EXPOSE 8100

# 启动应用
CMD ["python", "web_demo.py"]